name: HEROKU CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci # or yarn install
        uses: actions/checkout@master
      - name: login
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        with:
          args: container:login
      - name: set remote
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
        with:
          args: git:remote -a my-app
      - name: push
        run: git subtree push --prefix server heroku master
      # - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_TOKEN}}
      #     heroku_app_name: "cise-ci-cd" #Must be unique in Heroku
      #     heroku_email: "mgg7934@hotmail.com"
      #     remote_branch: "main"
      # - uses: CDNievas/heroku-action@v1.0 # This is the action
      #   with:
      #     heroku_email: "mgg7934@hotmail.com"
      #     heroku_api_key: ${{secrets.HEROKU_TOKEN}}
      #     heroku_app_name: "cise-ci-cd"
